apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zrsq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zrsq
    app.kubernetes.io/part-of: tkrw-pr712-0075-0051-app
  name: devfile-sample-zrsq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zrsq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zrsq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-zrsq@sha256:c65f41af86e612838fc97f6f473e9f96367ad607540163ad8833fdb88d4acc11
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
